This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./dissertacao.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dissertacao.acn....done (56 entries accepted, 0 rejected).
Sorting entries....done (334 comparisons).
Generating output file dissertacao.acr....done (54 lines written, 0 warnings).
Output written in dissertacao.acr.
Transcript written in dissertacao.alg.
