This is makeindex, version 2.15 [TeX Live 2019/dev] (kpathsea + Thai support).
Scanning style file ./dissertacao.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dissertacao.acn....done (515 entries accepted, 0 rejected).
Sorting entries.......done (5081 comparisons).
Generating output file dissertacao.acr....done (145 lines written, 0 warnings).
Output written in dissertacao.acr.
Transcript written in dissertacao.alg.
